'use client';
import { useState, useEffect, useCallback, useRef, type ReactNode, type FormEvent } from 'react';
import { Ticket, Compass, CalendarDays, LayoutDashboard, MapPin, Clock3, Search, Plus, X, Check, ChevronRight, Users, QrCode, LogOut, Code2, Palette, Music2, Trophy, BriefcaseBusiness, LoaderCircle, CircleAlert, Sparkles, RefreshCw, Download, Copy } from 'lucide-react';
import QRCode from 'qrcode';
import type { CampusData, CampusEvent, Booking } from '../lib/types';
const categories=['All events','Technology','Workshop','Culture','Sports','Career'];
const icons:Record<string,typeof Code2>={Technology:Code2,Workshop:Palette,Culture:Music2,Sports:Trophy,Career:BriefcaseBusiness};
const theme=(c:string)=>c.toLowerCase();
const fmt=(value:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',...options}).format(new Date(value));
const day=(value:string)=>fmt(value,{day:'2-digit'});
const month=(value:string)=>fmt(value,{month:'short'});
const date=(value:string)=>fmt(value,{weekday:'short',day:'numeric',month:'short'});
const time=(value:string)=>fmt(value,{hour:'numeric',minute:'2-digit'});
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>{d?.close();};},[]);
 return <dialog ref={ref} className={'modal '+(wide?'wide':'')} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} aria-label={title}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></div>{children}</dialog>;
}
function TicketQR({code}:{code:string}){
 const [src,setSrc]=useState('');
 useEffect(()=>{QRCode.toDataURL(window.location.origin+'/?checkin='+encodeURIComponent(code),{width:240,margin:2,color:{dark:'#142034',light:'#ffffff'}}).then(setSrc).catch(()=>setSrc(''));},[code]);
 return src?<img className="ticket-qr" src={src} alt="Ticket QR code for organizer check-in" width={200} height={200}/>:<p>Use the ticket code below for check-in.</p>;
}
export default function CampusApp(){
 const [data,setData]=useState<CampusData>({user:null,events:[],bookings:[]});
 const [view,setView]=useState('discover'),[category,setCategory]=useState('All events'),[query,setQuery]=useState(''),[period,setPeriod]=useState('upcoming');
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[authRequired,setAuthRequired]=useState(false),[busy,setBusy]=useState(false);
 const [notice,setNotice]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState<CampusEvent|null>(null),[ticket,setTicket]=useState<Booking|null>(null),[cancel,setCancel]=useState<Booking|null>(null);
 const [creating,setCreating]=useState(false),[checkin,setCheckin]=useState(false),[code,setCode]=useState(''),[attendeeEvent,setAttendeeEvent]=useState<CampusEvent|null>(null),[attendees,setAttendees]=useState<Booking[]|null>(null),[ticketTab,setTicketTab]=useState('active');
 const refresh=useCallback(async()=>{
   const response=await fetch('/api/campus',{cache:'no-store'});const body=await response.json() as CampusData & {error?:string};
   if(!response.ok){setAuthRequired(response.status===401);throw new Error(body.error||'Unable to load events.');}
   setData(body);setAuthRequired(false);setLoadError('');return body as CampusData;
 },[]);
 useEffect(()=>{refresh().catch(e=>setLoadError(e.message)).finally(()=>setLoading(false));const token=new URLSearchParams(window.location.search).get('checkin');if(token){setCode(token);setCheckin(true);setView('organizer');window.history.replaceState(null,'',window.location.pathname);}},[refresh]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 async function action(payload:Record<string,unknown>){
  setBusy(true);setError('');
  try{const r=await fetch('/api/campus',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json() as {error?:string;message:string;booking:Booking;attendees:Booking[]};if(!r.ok)throw new Error(b.error||'Please try again.');try{await refresh();}catch{setLoadError('Your change was saved, but the screen could not refresh. Please reload.');}setNotice(b.message);return b;}
  catch(e){setError(e instanceof Error?e.message:'Please try again.');return null;}finally{setBusy(false);}
 }
 function openEvent(e:CampusEvent){setError('');setSelected(e);}
 function navigate(v:string){setView(v);setError('');setQuery('');}
 const active=data.bookings.filter(b=>b.status!=='cancelled');
 const owned=data.events.filter(e=>e.owner_id===data.user?.id);
 const filtered=data.events.filter(e=>(category==='All events'||e.category===category)&&(e.title+' '+e.club+' '+e.venue).toLowerCase().includes(query.toLowerCase())&&(period==='all'||(period==='upcoming'?new Date(e.starts_at).getTime()>Date.now():new Date(e.starts_at).getTime()>Date.now()&&new Date(e.starts_at).getTime()<Date.now()+7*86400000)));
 const featured=data.events.find(e=>e.id==='sample-build-night'&&new Date(e.starts_at).getTime()>Date.now());
 const ticketEvent=ticket?data.events.find(e=>e.id===ticket.event_id):null;
 async function loadAttendees(e:CampusEvent){setAttendeeEvent(e);setAttendees(null);setError('');try{const r=await fetch('/api/campus?attendees='+encodeURIComponent(e.id));const b=await r.json() as {error?:string;message:string;booking:Booking;attendees:Booking[]};if(!r.ok)throw new Error(b.error);setAttendees(b.attendees);}catch(err){setError(err instanceof Error?err.message:'Unable to load attendees.');}}
 function downloadCalendar(e:CampusEvent){const stamp=(s:string)=>s.replace(/[-:]/g,'').replace(/\.\d{3}/,'');const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CampusPass//EN','BEGIN:VEVENT','UID:'+e.id+'@campuspass','DTSTAMP:'+stamp(new Date().toISOString()),'DTSTART:'+stamp(e.starts_at),'DTEND:'+stamp(e.ends_at),'SUMMARY:'+esc(e.title),'LOCATION:'+esc(e.venue),'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='campuspass-event.ics';a.click();URL.revokeObjectURL(url);}
 return <div className="app-shell">
  <aside className="sidebar">
   <button className="brand" onClick={()=>navigate('discover')}><span className="brand-mark"><Ticket size={25}/></span>Campus<span className="brand-light">Pass</span></button>
   <div className="workspace"><span className="campus-icon">C</span><div><strong>Campus community</strong><span>Find your next experience</span></div></div>
   <p className="nav-label">YOUR CAMPUS</p>
   <nav aria-label="Main navigation">
    <button className={view==='discover'?'nav-item selected':'nav-item'} onClick={()=>navigate('discover')}><Compass size={20}/>Discover events</button>
    <button className={view==='tickets'?'nav-item selected':'nav-item'} onClick={()=>navigate('tickets')}><Ticket size={20}/>My tickets<span className="nav-count">{active.length}</span></button>
    {data.user?.role==='organizer'&&<><p className="nav-label organizer-label">ORGANIZER SPACE</p><button className={view==='organizer'?'nav-item selected':'nav-item'} onClick={()=>navigate('organizer')}><LayoutDashboard size={19}/>Manage events</button></>}
   </nav>
   <div className="sidebar-bottom"><div className="side-note"><Sparkles size={21}/><strong>A little more campus life.</strong><p>Make something. Meet someone.<br/>Find your people.</p></div><div className="profile"><span className="avatar">{data.user?.name?.slice(0,1).toUpperCase()||'C'}</span><div><strong>{data.user?.name||'Welcome to CampusPass'}</strong><span>{data.user?.role==='organizer'?'Student & organizer':'Student account'}</span></div>{data.user&&<a href="/signout-with-chatgpt?return_to=/" target="_top" aria-label="Sign out"><LogOut size={17}/></a>}</div></div>
  </aside>
  <div className="main-wrap">
   <header className="topbar"><div className="breadcrumb">Campus community <ChevronRight size={14}/><strong>{view==='discover'?'Discover':view==='tickets'?'My tickets':'Organizer'}</strong></div><span className="term">2026 — 2027 <span>ACADEMIC YEAR</span></span></header>
   <main>
    <div className="page-heading"><div><span className="eyebrow">{view==='discover'?'GO BE PART OF SOMETHING':view==='tickets'?'YOUR NEXT EXPERIENCE':'BRING YOUR CAMPUS TOGETHER'}</span><h1>{view==='discover'?'Good things happen here.':view==='tickets'?'Your plans, in one place.':'Make it an event.'}</h1><p>{view==='discover'?'Workshops, big ideas, and everything in between.':view==='tickets'?'Your reservations and tickets, ready when you are.':'Create experiences and keep every registration in view.'}</p></div>{data.user?.role==='organizer'&&<button className="button primary create-top" onClick={()=>{setCreating(true);setError('');}}><Plus size={18}/>Create event</button>}</div>
    {loading?<div className="loading-panel"><LoaderCircle className="spin"/>Getting your campus ready…</div>:loadError?<div className="empty-panel"><CircleAlert size={32}/><h2>{authRequired?'Your campus is one sign-in away.':'Events are temporarily unavailable.'}</h2><p>{loadError}</p>{authRequired?<a className="button primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>:<button className="button primary" onClick={()=>{setLoading(true);refresh().catch(e=>setLoadError(e.message)).finally(()=>setLoading(false));}}><RefreshCw size={17}/>Try again</button>}</div>:<>
    {view==='discover'&&<>
     {featured&&category==='All events'&&!query&&<section className="featured"><div className="featured-content"><span className="feature-label"><span/>IN THE SPOTLIGHT <span className="sample-tag">Sample event</span></span><h2>Big ideas.<br/>One build night.</h2><p>Find your team. Build something that matters.</p><div className="feature-meta"><span><CalendarDays size={16}/>{date(featured.starts_at)}</span><span><MapPin size={16}/>Innovation Lab</span></div><button className="button light" onClick={()=>openEvent(featured)}>Explore event<ChevronRight size={16}/></button></div><div className="feature-ticket"><div className="ticket-topline">DEVELOPER CLUB <Code2 size={22}/></div><span className="feature-ticket-title">BUILD<br/>NIGHT<span className="orange-dot">.</span></span><div className="ticket-perf"/><div className="feature-ticket-bottom"><div><b>{day(featured.starts_at)}</b><span>{month(featured.starts_at)} {fmt(featured.starts_at,{year:'numeric'})}</span></div><span>MAKE IT<br/>HAPPEN.</span></div></div></section>}
     <section className="events-section" aria-label="Campus events"><div className="section-heading"><h2>Explore events <span>{filtered.length}</span></h2><span className="muted">All events are free to attend</span></div><div className="filter-toolbar"><div className="search-field"><Search size={18}/><input aria-label="Search events" placeholder="Search events, clubs, or venues" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="Clear search"><X size={15}/></button>}</div><select aria-label="Event date filter" value={period} onChange={e=>setPeriod(e.target.value)}><option value="upcoming">Upcoming events</option><option value="week">Next 7 days</option><option value="all">All dates</option></select></div><div className="category-tabs" aria-label="Event categories">{categories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'category active':'category'} onClick={()=>setCategory(c)}>{c}</button>)}</div>
     {filtered.length?<div className="events-grid">{filtered.map(e=>{const Icon=icons[e.category]||CalendarDays;const booked=active.some(b=>b.event_id===e.id);const remaining=e.capacity-e.reserved;return <article className="event-card" key={e.id}><button className={'card-art '+theme(e.category)} onClick={()=>openEvent(e)} aria-label={'View '+e.title}><span className="card-category"><Icon size={17}/>{e.category}</span><span className="card-date"><b>{day(e.starts_at)}</b>{month(e.starts_at)}</span><span className="art-word">{e.category==='Technology'?'CREATE.':e.category==='Workshop'?'EXPLORE.':e.category==='Culture'?'EXPRESS.':e.category==='Sports'?'PLAY.':'GROW.'}</span><span className="art-bottom">{e.club}</span></button><div className="card-content"><div className="card-host">{e.club}{e.sample===1&&<span>Sample</span>}</div><button className="card-title" onClick={()=>openEvent(e)}>{e.title}</button><p className="card-detail"><CalendarDays size={15}/>{date(e.starts_at)}<span>·</span>{time(e.starts_at)}</p><p className="card-detail"><MapPin size={15}/>{e.venue}</p><div className="card-footer"><span className={remaining<10?'seats low':'seats'}>{booked?<><Check size={14}/>You’re going</>:remaining>0?<><Users size={14}/>{remaining} spots left</>:'Fully booked'}</span><button className="text-button" onClick={()=>openEvent(e)}>View event<ChevronRight size={15}/></button></div></div></article>;})}</div>:<div className="empty-panel"><Search size={30}/><h3>No events match just yet.</h3><p>Try a different category, search, or date range.</p><button className="button secondary" onClick={()=>{setQuery('');setCategory('All events');setPeriod('all');}}>Reset filters</button></div>}
     </section>
    </>}
    {view==='tickets'&&<><div className="category-tabs"><button className={ticketTab==='active'?'category active':'category'} onClick={()=>setTicketTab('active')}>Reserved & checked in <span>{active.length}</span></button><button className={ticketTab==='cancelled'?'category active':'category'} onClick={()=>setTicketTab('cancelled')}>Cancelled</button></div><div className="ticket-list">{data.bookings.filter(b=>ticketTab==='active'?b.status!=='cancelled':b.status==='cancelled').map(b=>{const e=data.events.find(e=>e.id===b.event_id);if(!e)return null;return <article className="booking-card" key={b.id}><div className={'booking-date '+theme(e.category)}><b>{day(e.starts_at)}</b><span>{month(e.starts_at)}</span></div><div className="booking-info"><span className={'status '+b.status}>{b.status==='checked_in'?'Checked in':b.status==='cancelled'?'Cancelled':'Reserved'}</span><h2>{e.title}</h2><p>{date(e.starts_at)} · {time(e.starts_at)} IST</p><p><MapPin size={14}/>{e.venue}</p></div><div className="booking-actions">{b.status!=='cancelled'&&<><button className="button primary" onClick={()=>{setTicket(b);setError('');}}><QrCode size={17}/>View ticket</button><button className="text-button" onClick={()=>downloadCalendar(e)}><Download size={15}/>Add to calendar</button></>}{b.status==='confirmed'&&new Date(e.starts_at).getTime()>Date.now()&&<button className="text-button danger" onClick={()=>{setCancel(b);setError('');}}>Cancel reservation</button>}</div></article>;})}</div>{!data.bookings.some(b=>ticketTab==='active'?b.status!=='cancelled':b.status==='cancelled')&&<div className="empty-panel"><Ticket size={36}/><h2>{ticketTab==='active'?'Your next experience is waiting.':'No cancelled reservations.'}</h2><p>{ticketTab==='active'?'Discover something you love and reserve your first spot.':'Reservations you cancel will appear here.'}</p><button className="button primary" onClick={()=>navigate('discover')}>Discover events</button></div>}</>}
    {view==='organizer'&&(data.user?.role==='organizer'?<><div className="stats-grid"><div><span>YOUR EVENTS</span><strong>{owned.length}</strong><p>Experiences on campus</p></div><div><span>RESERVATIONS</span><strong>{owned.reduce((s,e)=>s+e.reserved,0)}</strong><p>Confirmed and checked in</p></div><div><span>CHECKED IN</span><strong>{owned.reduce((s,e)=>s+e.checked_in,0)}</strong><p>Ready to take part</p></div></div><section className="organizer-panel"><div className="section-heading"><div><h2>Your events</h2><p className="muted">Sample events are included so you can try every flow.</p></div><button className="button secondary" onClick={()=>{setCheckin(true);setError('');}}><QrCode size={18}/>Check in a ticket</button></div><div className="table-scroll"><table><thead><tr><th>EVENT</th><th>WHEN</th><th>RESERVATIONS</th><th>CHECK-IN</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{owned.map(e=><tr key={e.id}><td><strong>{e.title}</strong><span>{e.club}{e.sample?' · Sample event':''}</span></td><td>{date(e.starts_at)}<span>{time(e.starts_at)} IST</span></td><td><strong>{e.reserved} <span className="inline-muted">/ {e.capacity}</span></strong><progress max={e.capacity} value={e.reserved} aria-label={e.title+' reservations'}/></td><td>{e.checked_in}</td><td><button className="button small secondary" onClick={()=>loadAttendees(e)}>Attendees</button></td></tr>)}</tbody></table></div></section></>:<div className="empty-panel"><LayoutDashboard size={32}/><h2>Organizer access required</h2><p>You can discover events and reserve tickets with your student account.</p><button className="button primary" onClick={()=>navigate('discover')}>Discover events</button></div>)}
    </>}
    <footer><span><Ticket size={15}/>CampusPass</span><span>Made for campus life. <span className="footer-time">All times in India Standard Time.</span></span></footer>
   </main>
  </div>
  {notice&&<div className="toast" role="status"><span><Check size={19}/></span>{notice}<button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={17}/></button></div>}
  {selected&&<Modal title="Event details" onClose={()=>{if(!busy)setSelected(null);}}><div className={'detail-banner '+theme(selected.category)}><span className="pill">{selected.category}</span><h2>{selected.title}</h2><span>{selected.club}{selected.sample?' · Sample event':''}</span></div><div className="modal-body"><div className="detail-facts"><div><CalendarDays/><span><strong>{date(selected.starts_at)}</strong>{time(selected.starts_at)} – {time(selected.ends_at)} IST</span></div><div><MapPin/><span><strong>{selected.venue}</strong>On campus</span></div><div><Users/><span><strong>{data.events.find(e=>e.id===selected.id)?.capacity!-(data.events.find(e=>e.id===selected.id)?.reserved||0)} spots remaining</strong>Free entry · One ticket per person</span></div></div><h3>About this event</h3><p className="description">{selected.description}</p>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions">{active.some(b=>b.event_id===selected.id)?<button className="button primary full" onClick={()=>{setTicket(active.find(b=>b.event_id===selected.id)!);setSelected(null);}}><Ticket size={18}/>View your ticket</button>:<button className="button primary full" disabled={busy||new Date(selected.starts_at).getTime()<=Date.now()||(data.events.find(e=>e.id===selected.id)?.reserved||0)>=selected.capacity} onClick={async()=>{const r=await action({action:'reserve',eventId:selected.id});if(r){setSelected(null);setTicket(r.booking);}}}>{busy?<LoaderCircle className="spin" size={18}/>:<Ticket size={18}/>}Reserve my spot</button>}</div><p className="fine-print">You can cancel before the event begins.</p></div></Modal>}
  {ticket&&ticketEvent&&<Modal title="Your CampusPass" onClose={()=>setTicket(null)}><div className="digital-ticket"><span className={'status '+ticket.status}>{ticket.status==='checked_in'?'Checked in':'Reservation confirmed'}</span><h2>{ticketEvent.title}</h2><p>{date(ticketEvent.starts_at)} · {time(ticketEvent.starts_at)} IST</p><p>{ticketEvent.venue}</p><div className="qr-area"><TicketQR code={ticket.code}/></div><strong>{data.user?.name}</strong><p className="fine-print">Show this QR code to the event organizer.</p><div className="code-box"><code>{ticket.code}</code><button className="icon-button" aria-label="Copy ticket code" onClick={async()=>{try{await navigator.clipboard.writeText(ticket.code);setNotice('Ticket code copied.');}catch{setError('Select the ticket code above to copy it.');}}}><Copy size={17}/></button></div>{error&&<p className="error">{error}</p>}<button className="button secondary full" onClick={()=>downloadCalendar(ticketEvent)}><Download size={17}/>Add to calendar</button></div></Modal>}
  {cancel&&<Modal title="Cancel this reservation?" onClose={()=>{if(!busy)setCancel(null);}}><div className="modal-body"><p>Your seat will become available to another student. You can reserve again if a spot is still available.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setCancel(null)}>Keep my ticket</button><button className="button danger-button" disabled={busy} onClick={async()=>{if(await action({action:'cancel',bookingId:cancel.id}))setCancel(null);}}>{busy?'Cancelling…':'Cancel reservation'}</button></div></div></Modal>}
  {creating&&<Modal title="Create a campus event" wide onClose={()=>{if(!busy)setCreating(false);}}><form className="modal-body event-form" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const start=String(f.get('startsAt')),end=String(f.get('endsAt'));const r=await action({action:'create',...Object.fromEntries(f),startsAt:new Date(start+':00+05:30').toISOString(),endsAt:new Date(end+':00+05:30').toISOString()});if(r){setCreating(false);setView('organizer');}}}><p className="muted">Give students something to look forward to. All events are free.</p><label>Event title<input name="title" required minLength={4} maxLength={100} placeholder="e.g. Build your first web app"/></label><div className="form-grid"><label>Category<select name="category">{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Club or organizer<input name="club" required minLength={2} maxLength={80} placeholder="e.g. Developer Club"/></label></div><label>Venue<input name="venue" required minLength={2} maxLength={120} placeholder="Building, room, or campus space"/></label><div className="form-grid"><label>Starts at (IST)<input name="startsAt" type="datetime-local" required/></label><label>Ends at (IST)<input name="endsAt" type="datetime-local" required/></label></div><label>Capacity<input name="capacity" type="number" required min="1" max="10000" defaultValue="50"/></label><label>About the event<textarea name="description" required minLength={20} maxLength={3000} rows={4} placeholder="What will students do? Who is it for? What should they bring?"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={()=>setCreating(false)}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Publishing…':'Publish event'}<Plus size={17}/></button></div></form></Modal>}
  {checkin&&<Modal title="Check in a ticket" onClose={()=>{if(!busy)setCheckin(false);}}><form className="modal-body event-form" onSubmit={async e=>{e.preventDefault();let value=code.trim();try{value=new URL(value).searchParams.get('checkin')||value;}catch{}if(await action({action:'checkin',code:value})){setCode('');setCheckin(false);}}}><div className="checkin-symbol"><QrCode size={40}/></div><p>Scan a ticket’s QR code with your phone camera, or paste its ticket code here. Only the event organizer can check it in.</p><label>Ticket code<input value={code} onChange={e=>setCode(e.target.value)} required placeholder="Paste ticket code or QR link" autoComplete="off"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy||data.user?.role!=='organizer'}>{busy?'Checking ticket…':'Confirm check-in'}<Check size={18}/></button></form></Modal>}
  {attendeeEvent&&<Modal title="Event attendees" wide onClose={()=>setAttendeeEvent(null)}><div className="modal-body"><h3>{attendeeEvent.title}</h3><p className="muted">{date(attendeeEvent.starts_at)} · {time(attendeeEvent.starts_at)} IST</p>{error&&<p className="error" role="alert">{error}</p>}{!attendees&&!error?<p className="loading-panel">Loading attendees…</p>:attendees?.length?<div className="attendee-list">{attendees.map(b=><div className="attendee" key={b.id}><span className="avatar">{b.name?.slice(0,1).toUpperCase()}</span><div><strong>{b.name}</strong><span>{b.email}</span></div>{b.status==='checked_in'?<span className="status checked_in">Checked in</span>:<button className="button small secondary" disabled={busy} onClick={async()=>{if(await action({action:'checkin',code:b.code}))await loadAttendees(attendeeEvent);}}>Check in</button>}</div>)}</div>:!error&&<div className="empty-panel"><Users size={30}/><h3>No reservations yet.</h3><p>Students will appear here when they reserve a spot.</p></div>}</div></Modal>}
 </div>;
}
