export function sampleEvents(ownerId:string) {
  const base = new Date();
  const date=(offset:number,hour:number)=>new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),base.getUTCDate()+offset,hour-5,30)).toISOString();
  return [
    {id:'sample-build-night',title:'Build Night: ideas to impact',category:'Technology',club:'Developer Club',venue:'Innovation Lab · Block A',description:'An evening for makers. Bring an idea, find a small team, and turn it into a working prototype. We will kick off with a short ideation session, build together, and finish with five-minute demos. All experience levels are welcome. Bring your laptop and charger.',offset:5,hour:17,duration:4,capacity:60},
    {id:'sample-design',title:'Design beyond the screen',category:'Workshop',club:'Design Collective',venue:'Studio 204 · Block B',description:'Explore how good product design starts with people. Practice quick user interviews, map a real problem, and sketch your first solution in a hands-on workshop. No design tools or prior experience required.',offset:3,hour:14,duration:2,capacity:35},
    {id:'sample-openmic',title:'The campus open mic',category:'Culture',club:'Arts & Culture Society',venue:'Open-air Amphitheatre',description:'Poetry, acoustic music, storytelling, and a little campus magic. Reserve a place in the audience and support your campus creatives. Performers can sign up with the host at the venue.',offset:6,hour:18,duration:2,capacity:120},
    {id:'sample-ai',title:'AI builders: first steps',category:'Technology',club:'AI & ML Club',venue:'Computer Lab 3',description:'Build your first text classifier and learn how to tell whether it works. A practical introduction to datasets, training, evaluation, and common mistakes. Basic Python knowledge is helpful. Bring your laptop.',offset:8,hour:10,duration:3,capacity:45},
    {id:'sample-badminton',title:'Campus badminton social',category:'Sports',club:'Sports Committee',venue:'Indoor Sports Arena',description:'Meet new players over friendly doubles matches. Open to beginners and experienced players alike. Teams will be paired at the venue. Wear court shoes and bring water; shared racquets are available.',offset:10,hour:16,duration:2,capacity:32},
    {id:'sample-career',title:'Inside the engineering interview',category:'Career',club:'Career Development Cell',venue:'Seminar Hall · Block C',description:'Practice explaining your approach, working through a coding problem, and discussing a project. Join a small-group mock interview followed by constructive feedback. Bring one project you would like to talk about.',offset:12,hour:11,duration:2,capacity:50},
  ].map(e=>({...e,ownerId,startsAt:date(e.offset,e.hour),endsAt:date(e.offset,e.hour+e.duration)}));
}
